Anexos da diligência única
secultce/mapasculturais-v5 pull request #94
Opened 2024-06-10 17:34 UTC by jeff-doliveira1

### Issues relacionadas 

[https://github.com/secultce/mapasculturais-v5/issues/54](url)
[https://github.com/secultce/mapasculturais-v5/issues/92](url)

2024-06-10 19:29 UTC, ronnyjohnti requested changes
Fiz só uma solicitação de alteração.

2024-06-10 19:29 UTC, ronnyjohnti commented on src/protected/application/lib/modules/Diligence/Controllers/Controller.php
> +                if ($result) {
Pra evitar SQL Injection, melhor utilizar bindParam.

```suggestion
                $stmt = $conn->prepare('DELETE FROM file WHERE id = :id');
                $stmt->bindParam('id', $this->data['id']);
                $affectedRows = $stmt->executeStatement();
                
                if ($affectedRows) {
```

2024-06-10 19:46 UTC, ronnyjohnti approved these changes

2024-06-11 19:16 UTC, Junior-Shyko approved these changes

2024-06-11 19:22 UTC, merged